spring:
  datasource:
    url: jdbc:mysql://minji-board-rds.cprq7tgal4rf.us-east-1.rds.amazonaws.com:3306/board
    username: ${USER}
    password: ${PWD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: info
